<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>Foundry</AssemblyName>
    <RootNamespace>Foundry.Desktop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Foundry.Host\Foundry.Host.csproj" />
  </ItemGroup>
</Project>
