// Spike S4's oracle, run in the test page and in each of its frames. It counts every trusted event of the listed types
// in this frame. Untrusted events, such as the agent's host scripts dispatch, are counted apart. Input events come only
// from input; hover, focus and scroll events can also be generated by the browser itself (a layout change under a
// resting cursor, a window activation), so they are kept separate and shown, not hidden.
const S4_INPUT = ['pointerdown', 'pointerup', 'pointercancel', 'gotpointercapture', 'lostpointercapture', 'mousedown', 'mouseup',
  'click', 'dblclick', 'auxclick', 'contextmenu', 'wheel', 'mousewheel', 'keydown', 'keyup', 'keypress', 'beforeinput', 'input',
  'textInput', 'change', 'compositionstart', 'compositionupdate', 'compositionend', 'paste', 'copy', 'cut', 'select', 'selectstart',
  'dragstart', 'drag', 'dragend', 'dragenter', 'dragover', 'dragleave', 'drop', 'touchstart', 'touchmove', 'touchend', 'touchcancel'];
const S4_HOVER = ['pointermove', 'pointerrawupdate', 'pointerover', 'pointerout', 'pointerenter', 'pointerleave', 'mousemove',
  'mouseover', 'mouseout', 'mouseenter', 'mouseleave', 'focus', 'blur', 'focusin', 'focusout', 'scroll'];
const recorder = { input: {}, hover: {}, synthetic: 0, last: [] };
function s4Record(event) {
  if (!event.isTrusted) { recorder.synthetic++; return; }
  const bucket = S4_INPUT.includes(event.type) ? recorder.input : recorder.hover;
  bucket[event.type] = (bucket[event.type] ?? 0) + 1;
  recorder.last.unshift(`${new Date().toISOString().slice(11, 23)} ${S4_NAME} ${event.type}`);
  recorder.last.length = Math.min(recorder.last.length, 6);
  s4Changed();
}
// Capture listeners on the window see every event dispatched in this document, bubbling or not.
for (const type of [...S4_INPUT, ...S4_HOVER]) window.addEventListener(type, s4Record, { capture: true, passive: true });
// Accept drops, so a drop that does reach the page is counted rather than navigating the tab away.
for (const type of ['dragover', 'drop']) window.addEventListener(type, event => event.preventDefault());
